package de.geffeniuse.gac.check.combat;

import com.comphenix.protocol.PacketType;
import com.comphenix.protocol.events.PacketEvent;
import com.comphenix.protocol.wrappers.EnumWrappers;
import de.geffeniuse.gac.check.Check;
import de.geffeniuse.gac.data.GACUser;
import org.bukkit.entity.Player;

public class AimB extends Check {

    private final float EXPANDER = Math.scalb(1.0f, 24); // 2^24
    private int suspicion = 0;
    private long lastAttackTime = 0;

    public AimB(GACUser user) {
        super(user, "Aim (GCD)", "Checks if rotation matches valid mouse input.");
    }

    @Override
    public void onPacket(PacketEvent event) {
        // Track attacks
        if (event.getPacketType() == PacketType.Play.Client.USE_ENTITY) {
            try {
                EnumWrappers.EntityUseAction action = event.getPacket().getEnumEntityUseActions().read(0).getAction();
                if (action == EnumWrappers.EntityUseAction.ATTACK) {
                    lastAttackTime = System.currentTimeMillis();
                }
            } catch (Exception ignored) {}
            return;
        }

        if (event.getPacketType() != PacketType.Play.Client.LOOK &&
            event.getPacketType() != PacketType.Play.Client.POSITION_LOOK) return;

        Player player = user.getPlayer();
        if (player == null) return;

        // ONLY check when player is in combat (attacked in last 3 seconds)
        long timeSinceAttack = System.currentTimeMillis() - lastAttackTime;
        if (timeSinceAttack > 3000) {
            suspicion = Math.max(0, suspicion - 2);
            return;
        }

        float deltaYaw = user.getDeltaYaw();
        float deltaPitch = user.getDeltaPitch();

        // Only check valid movement (not extremely small or extremely large)
        if (deltaPitch > 0.1 && deltaPitch < 20.0 && deltaYaw > 0.1 && deltaYaw < 20.0) {
            
            long deltaYawLong = (long) (deltaYaw * EXPANDER);
            long deltaPitchLong = (long) (deltaPitch * EXPANDER);

            long gcd = getGcd(deltaYawLong, deltaPitchLong);
            
            // This is complex math magic.
            // If the movement is generated by Minecraft client mouse input, GCD should be high relative to movement.
            // If generated by AimAssist (float math), GCD is often very small (1).
            
            // We use a heuristic: if GCD is very small compared to the pitch change, it's likely generated.
            // (Note: This is simplified. Real GCD checks deduce sensitivity.)
            
            // Let's use a simpler "Sensitivity Constant" approach
            // If we can find a sens X where deltaYaw = X * m_yaw and deltaPitch = X * m_pitch
            // it's legit. If not, it's strange.
            
            // For this version, let's stick to the classic "small GCD" heuristic for now.
            if (gcd < 131072L) { // Heuristic threshold
                 suspicion++;
            } else {
                 suspicion = Math.max(0, suspicion - 1);
            }

            if (suspicion > 15) {
                // fail("input invalid"); // Commented out to avoid false positives without proper sensitivity derivation
                // This check needs calibration. Enabling it raw might ban legit players with weird DPI.
                // Let's activate a simpler heuristic instead: PITCH SNAPPING
            }
        }
    }
    
    private long getGcd(long a, long b) {
        return (b == 0) ? a : getGcd(b, a % b);
    }
}
